import '@navikt/ds-css';
import { fetchDecoratorReact } from '@navikt/nav-dekoratoren-moduler/ssr';
import { getEnvironment } from 'lib/utils/environments';
import Script from 'next/script';

export const metadata = {
  title: 'Mine AAP',
  //description: 'Generated by Next.js',
};
const RootLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
  const Decorator = await fetchDecoratorReact({ env: getEnvironment() });

  return (
    <html lang="nb">
      <head>
        <Decorator.HeadAssets />
      </head>
      <body>
        <Decorator.Header />
        {children}
        <Decorator.Footer />
        <Decorator.Scripts loader={Script} />
      </body>
    </html>
  );
};

export default RootLayout;
