import { Heading } from '@navikt/ds-react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>AAP - Innsyn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading level="1" size="xlarge">
          Innsynsløsning
        </Heading>
      </main>
    </>
  );
};

export default Home;
